add_newline = false


format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$character
"""
right_format = """
$time"""

[directory]
truncate_to_repo = false
truncation_length = 0

[time]
disabled = false
format = "[ $time]($style)"

# Disable noisy modules by default
[aws]
disabled = true

[python]
disabled = true  # Avoids false Python version triggers :cite[3]

[nodejs]
disabled = true

[package]
disabled = true  # Hides package version info :cite[8]

# Simplify Git module: show only branch/state
[git_branch]
format = "[$branch]($style) "

